services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: quiz-assessment-app
    restart: unless-stopped
    ports:
      - "${APP_PORT:-8080}:8080"
    environment:
      APP_ENV: local
      APP_DEBUG: "true"
      APP_KEY: "${APP_KEY}"

      DB_CONNECTION: pgsql
      DB_HOST: postgres
      DB_PORT: 5432
      DB_DATABASE: quiz_assessment
      DB_USERNAME: postgres
      DB_PASSWORD: postgres

    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres:17-alpine
    container_name: quiz-assessment-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: quiz_assessment
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U postgres -d quiz_assessment"
        ]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  postgres_data: